NASM       ?= nasm
CC         ?= gcc
LD         ?= ld
OBJCOPY    ?= objcopy
HOST_CC    ?= cc

CONFLICT_CHECK := ./scripts/check-conflicts.sh

# Added -MMD -MP for automatic dependency tracking
CFLAGS := -std=gnu11 -O2 -ffreestanding -fno-stack-protector -fcf-protection=none \
          -fno-pic -mno-red-zone -mgeneral-regs-only -nostdlib -nostartfiles \
          -Wall -Wextra -Ikernel/include -mno-mmx -mno-sse -mno-sse2 -mno-sse3 \
          -mno-ssse3 -mno-sse4 -mno-avx -MMD -MP
NASMFLAGS := -Wall -Werror

BUILD_DIR := build
BOOT_BIN := $(BUILD_DIR)/boot.bin
STAGE2_BIN := $(BUILD_DIR)/stage2.bin
KERNEL_ELF := $(BUILD_DIR)/kernel.elf
KERNEL_BIN := $(BUILD_DIR)/kernel.bin
PAYLOAD_BIN := $(BUILD_DIR)/stage2_kernel.bin
OS_IMAGE := $(BUILD_DIR)/NostaluxOS.img
KERNEL_EXCLUDED_SRCS := kernel/window_manager.c
KERNEL_SRCS := $(filter-out $(KERNEL_EXCLUDED_SRCS),$(wildcard kernel/*.c))
KERNEL_OBJS := $(patsubst kernel/%.c,$(BUILD_DIR)/%.o,$(KERNEL_SRCS))

# Include dependency files generated by GCC
DEPS := $(KERNEL_OBJS:.o=.d)

QEMU ?= qemu-system-x86_64
QEMU_NATIVE ?=

# Interactive runs prefer a native Windows QEMU executable when one can be
# discovered. Linux QEMU remains the portable fallback and powers headless runs.
QEMU_AUDIO_LINUX ?= -machine pcspk-audiodev=snd0 -audiodev pa,id=snd0
QEMU_AUDIO_NATIVE ?= -machine pcspk-audiodev=snd0 -audiodev dsound,id=snd0
QEMU_AUDIO_HEADLESS ?= -machine pcspk-audiodev=snd0 -audiodev none,id=snd0
# GTK keeps Windows physical X/Y motion in one frontend path, hides the host
# pointer, and preserves a 1:1 guest framebuffer scale. Hover grab also keeps
# keyboard focus with the guest while the pointer is over the display.
QEMU_DISPLAY_FULLSCREEN ?= -display gtk,full-screen=on,grab-on-hover=on,show-cursor=off,show-tabs=off,show-menubar=off,zoom-to-fit=on
QEMU_DISPLAY_WINDOWED ?= -display gtk,grab-on-hover=on,show-cursor=off,show-tabs=off,show-menubar=off,zoom-to-fit=off
QEMU_DISPLAY_HEADLESS ?= -display none -serial mon:stdio

# The ATA-backed flat filesystem begins at LBA 2048. Preserve everything from
# that offset onward when replacing the bootloader/kernel during a normal build.
FS_STORAGE_LBA ?= 2048
IMAGE_DATA_MIB ?= 32

define RUN_QEMU
	@set -eu; \
	if [ "$(HEADLESS)" = "1" ]; then \
		if command -v "$(QEMU)" >/dev/null 2>&1; then \
			echo "Running headless with $(QEMU)"; \
			exec "$(QEMU)" $(QEMU_DISPLAY_HEADLESS) $(QEMU_AUDIO_HEADLESS) \
				-drive format=raw,file=$(OS_IMAGE); \
		fi; \
		echo "Error: $(QEMU) was not found. Set QEMU=/path/to/qemu-system-x86_64." >&2; \
		exit 1; \
	fi; \
	native_qemu='$(QEMU_NATIVE)'; \
	if [ -z "$$native_qemu" ]; then \
		native_qemu=$$(command -v qemu-system-x86_64.exe 2>/dev/null || true); \
	fi; \
	if [ -z "$$native_qemu" ]; then \
		for candidate in \
			"/mnt/c/Program Files/qemu/qemu-system-x86_64.exe" \
			"/mnt/c/Program Files (x86)/qemu/qemu-system-x86_64.exe" \
			"/c/Program Files/qemu/qemu-system-x86_64.exe" \
			"/c/Program Files (x86)/qemu/qemu-system-x86_64.exe"; do \
			if [ -x "$$candidate" ]; then \
				native_qemu="$$candidate"; \
				break; \
			fi; \
		done; \
	fi; \
	if [ -n "$$native_qemu" ] && [ -x "$$native_qemu" ]; then \
		echo "Running with native Windows QEMU: $$native_qemu"; \
		exec "$$native_qemu" $(1) $(QEMU_AUDIO_NATIVE) \
			-drive format=raw,file=$(OS_IMAGE); \
	fi; \
	if command -v "$(QEMU)" >/dev/null 2>&1; then \
		echo "Native Windows QEMU not found; using $(QEMU)."; \
		exec "$(QEMU)" $(1) $(QEMU_AUDIO_LINUX) \
			-drive format=raw,file=$(OS_IMAGE); \
	fi; \
	echo "Error: no QEMU executable found. Install QEMU or set QEMU_NATIVE/QEMU." >&2; \
	exit 1
endef

.PHONY: all clean test test-bmp run run-windowed run-fullscreen check-conflicts

all: check-conflicts $(OS_IMAGE)

check-conflicts:
	@$(CONFLICT_CHECK)

test: test-bmp

test-bmp: | $(BUILD_DIR)
	$(HOST_CC) -std=c11 -Wall -Wextra -Werror -Ikernel/include \
		tests/bmp_test.c kernel/bmp.c -o $(BUILD_DIR)/bmp_test
	$(BUILD_DIR)/bmp_test

$(BUILD_DIR):
	@mkdir -p $(BUILD_DIR)

$(KERNEL_ELF): kernel/entry.asm $(KERNEL_OBJS) kernel/linker.ld | $(BUILD_DIR)
	$(NASM) -f elf64 kernel/entry.asm -o $(BUILD_DIR)/entry.o
	$(LD) -nostdlib -z max-page-size=0x1000 -T kernel/linker.ld -o $@ $(BUILD_DIR)/entry.o $(KERNEL_OBJS)

$(BUILD_DIR)/%.o: kernel/%.c Makefile | $(BUILD_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

$(KERNEL_BIN): $(KERNEL_ELF) | $(BUILD_DIR)
	$(OBJCOPY) -O binary $(KERNEL_ELF) $@

$(STAGE2_BIN): bootloader/stage2.asm $(KERNEL_BIN) | $(BUILD_DIR)
	@KERNEL_SIZE=$$(stat -c%s $(KERNEL_BIN)); \
	$(NASM) -f bin $(NASMFLAGS) -DKERNEL_SIZE_BYTES=$$KERNEL_SIZE bootloader/stage2.asm -o $@

$(PAYLOAD_BIN): $(STAGE2_BIN) $(KERNEL_BIN) | $(BUILD_DIR)
	cat $(STAGE2_BIN) $(KERNEL_BIN) > $@

$(BOOT_BIN): bootloader/boot.asm $(PAYLOAD_BIN) | $(BUILD_DIR)
	@TOTAL_SIZE=$$(stat -c%s $(PAYLOAD_BIN)); \
	TOTAL_SECTORS=$$(( (TOTAL_SIZE + 511) / 512 )); \
	$(NASM) -f bin $(NASMFLAGS) -DTOTAL_SECTORS=$$TOTAL_SECTORS bootloader/boot.asm -o $@

$(OS_IMAGE): $(BOOT_BIN) $(PAYLOAD_BIN)
	@set -eu; \
	TMP_IMAGE=$$(mktemp '$@.tmp.XXXXXX'); \
	SAVED_STORAGE=$$(mktemp '$@.storage.tmp.XXXXXX'); \
	FS_OFFSET=$$(( $(FS_STORAGE_LBA) * 512 )); \
	MIN_IMAGE_SIZE=$$(( FS_OFFSET + $(IMAGE_DATA_MIB) * 1024 * 1024 )); \
	trap 'rm -f "$$TMP_IMAGE" "$$SAVED_STORAGE"' 0 1 2 15; \
	if [ -f '$@' ]; then \
		OLD_SIZE=$$(stat -c%s '$@'); \
		if [ "$$OLD_SIZE" -gt "$$FS_OFFSET" ]; then \
			dd if='$@' of="$$SAVED_STORAGE" bs=512 skip=$(FS_STORAGE_LBA) 2>/dev/null; \
		fi; \
	fi; \
	cat $(BOOT_BIN) $(PAYLOAD_BIN) > "$$TMP_IMAGE"; \
	BOOT_END=$$(stat -c%s "$$TMP_IMAGE"); \
	if [ "$$BOOT_END" -gt "$$FS_OFFSET" ]; then \
		echo "Error: boot payload ($$BOOT_END bytes) overlaps filesystem LBA $(FS_STORAGE_LBA)." >&2; \
		exit 1; \
	fi; \
	truncate -s "$$FS_OFFSET" "$$TMP_IMAGE"; \
	if [ -s "$$SAVED_STORAGE" ]; then \
		cat "$$SAVED_STORAGE" >> "$$TMP_IMAGE"; \
	fi; \
	IMAGE_SIZE=$$(stat -c%s "$$TMP_IMAGE"); \
	if [ "$$IMAGE_SIZE" -lt "$$MIN_IMAGE_SIZE" ]; then \
		truncate -s "$$MIN_IMAGE_SIZE" "$$TMP_IMAGE"; \
	fi; \
	mv "$$TMP_IMAGE" '$@'; \
	rm -f "$$SAVED_STORAGE"; \
	trap - 0 1 2 15

clean:
	rm -rf $(BUILD_DIR)

run: check-conflicts $(OS_IMAGE)
	$(call RUN_QEMU,$(QEMU_DISPLAY_WINDOWED))

run-windowed: check-conflicts $(OS_IMAGE)
	$(call RUN_QEMU,$(QEMU_DISPLAY_WINDOWED))

run-fullscreen: check-conflicts $(OS_IMAGE)
	$(call RUN_QEMU,$(QEMU_DISPLAY_FULLSCREEN))

-include $(DEPS)
